services:
  preview:
    image: python:3.11-alpine   
    container_name: preview-dev
    environment:
      - AUTH_USER=mickey
      - AUTH_PASS=1
    volumes:
      - ./:/app:ro            
      - /:/host:ro                
    working_dir: /app
    command: python3 preview.py
    ports:
      - "6034:6033"
    restart: unless-stopped